services:
  mongodb:
    image: mongo:7
    container_name: webflux-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: webflux_demo
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval 'db.adminCommand("ping")'
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      - webflux-network

  app:
    build: .
    container_name: webflux-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: webflux_demo
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - webflux-network

volumes:
  mongodb_data:

networks:
  webflux-network:
    driver: bridge